apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    dockerdev: db
data:
  POSTGRES_DB: crier
  POSTGRES_USER: crier
  POSTGRES_PASSWORD: crier
  sql-init: |
    CREATE TABLE IF NOT EXISTS visitors(
                                           id serial constraint visitors_pk primary key,
                                           user_agent varchar(250),
                                           datetime timestamp
    );

    CREATE INDEX IF NOT EXISTS visitors_user_agent_index ON visitors (user_agent);
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    dockerdev: db
  name: db
spec:
  serviceName: dockerdev-db
  selector:
    matchLabels:
      dockerdev: db
  template:
    metadata:
      labels:
        dockerdev: db
    spec:
      containers:
        - name: db
          image: postgres:12.3-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        -  name: db-init
           configMap:
             name: db-config
             items:
               - key: sql-init
                 path: init.sql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    dockerdev: db
  name: dockerdev-db-exported
spec:
  type: NodePort
  ports:
    - name: 5432-tcp
      port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    dockerdev: db