#!/bin/bash

# stolen from https://sookocheff.com/post/bash/parsing-bash-script-arguments-with-shopts/

while getopts ":h" opt; do
  case ${opt} in
    h )
      echo "Usage:"
      echo "    $0 -h                     Display this help message."
      echo "    $0 create                 Creates new environment on the localhost."
      echo "    $0 destroy                Destroys environment on the localhost."
      echo "    $0 port-forward           Forwards interesting ports to the localhost."
      exit 0
      ;;
   \? )
     echo "Invalid Option: -$OPTARG" 1>&2
     exit 1
     ;;
   : )
     echo "Invalid Option: -$OPTARG requires an argument."
     exit 1
     ;;
   esac
done
shift $((OPTIND -1))

subcommand=$1; shift
case "$subcommand" in
  create)
#    kubectl create -f postgres-configmap.yaml
    kubectl create configmap
    kubectl create -f ../resources/db.yaml
    exit $?
    ;;
  destroy)
    kubectl delete -f ../resources/db.yaml
    exit $?
    ;;
  port-forward)
    while getopts "p:" opt; do
      case ${opt} in
        p )
          port=$OPTARG
          kubectl port-forward pod/db0 $port:5432&
          exit 0
          ;;
        \? )
          Invalid Option: -$OPTARG" 1>&2"
          exit 1
          ;;
      esac
    done
    kubectl port-forward pod/db0 5432:5432&
    exit0
    ;;
esac

